// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CleanupOutdatedCaches: typeof import('./theme/components/CleanupOutdatedCaches.md')['default']
    ExamplesBehaviors: typeof import('./theme/components/ExamplesBehaviors.md')['default']
    ExamplesGenerateSW: typeof import('./theme/components/ExamplesGenerateSW.md')['default']
    ExamplesInjectManifest: typeof import('./theme/components/ExamplesInjectManifest.md')['default']
    GenerateSWCleanupOutdatedCaches: typeof import('./theme/components/GenerateSWCleanupOutdatedCaches.md')['default']
    GenerateSWSourceMap: typeof import('./theme/components/GenerateSWSourceMap.md')['default']
    HeuristicWorkboxWindow: typeof import('./theme/components/HeuristicWorkboxWindow.md')['default']
    HomePage: typeof import('./theme/components/HomePage.vue')['default']
    InjectManifestCleanupOutdatedCaches: typeof import('./theme/components/InjectManifestCleanupOutdatedCaches.md')['default']
    InjectManifestSourceMap: typeof import('./theme/components/InjectManifestSourceMap.md')['default']
    PromptForUpdateImg: typeof import('./theme/components/PromptForUpdateImg.vue')['default']
    ReloadPrompt: typeof import('./theme/components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunExamples: typeof import('./theme/components/RunExamples.md')['default']
    SsrSsg: typeof import('./theme/components/SsrSsg.md')['default']
    TypeScriptError2307: typeof import('./theme/components/TypeScriptError2307.md')['default']
  }
}
