// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArrowLeft: typeof import('./theme/components/icons/ArrowLeft.vue')['default']
    ArrowRight: typeof import('./theme/components/icons/ArrowRight.vue')['default']
    CleanupOutdatedCaches: typeof import('./theme/components/CleanupOutdatedCaches.md')['default']
    DarkModeSwitch: typeof import('./theme/components/DarkModeSwitch.vue')['default']
    EditLink: typeof import('./theme/components/EditLink.vue')['default']
    ExamplesBehaviors: typeof import('./theme/components/ExamplesBehaviors.md')['default']
    ExamplesGenerateSW: typeof import('./theme/components/ExamplesGenerateSW.md')['default']
    ExamplesInjectManifest: typeof import('./theme/components/ExamplesInjectManifest.md')['default']
    GenerateSWCleanupOutdatedCaches: typeof import('./theme/components/GenerateSWCleanupOutdatedCaches.md')['default']
    GenerateSWSourceMap: typeof import('./theme/components/GenerateSWSourceMap.md')['default']
    HeuristicWorkboxWindow: typeof import('./theme/components/HeuristicWorkboxWindow.md')['default']
    Home: typeof import('./theme/components/Home.vue')['default']
    HomeFeatures: typeof import('./theme/components/HomeFeatures.vue')['default']
    HomeFooter: typeof import('./theme/components/HomeFooter.vue')['default']
    HomeHero: typeof import('./theme/components/HomeHero.vue')['default']
    InjectManifestCleanupOutdatedCaches: typeof import('./theme/components/InjectManifestCleanupOutdatedCaches.md')['default']
    InjectManifestSourceMap: typeof import('./theme/components/InjectManifestSourceMap.md')['default']
    MdListAnchor: typeof import('./theme/components/MdListAnchor.vue')['default']
    NavBar: typeof import('./theme/components/NavBar.vue')['default']
    NavBarTitle: typeof import('./theme/components/NavBarTitle.vue')['default']
    NavDropdownLink: typeof import('./theme/components/NavDropdownLink.vue')['default']
    NavDropdownLinkItem: typeof import('./theme/components/NavDropdownLinkItem.vue')['default']
    NavLink: typeof import('./theme/components/NavLink.vue')['default']
    NavLinks: typeof import('./theme/components/NavLinks.vue')['default']
    NextAndPrevLinks: typeof import('./theme/components/NextAndPrevLinks.vue')['default']
    Note: typeof import('./theme/components/Note.vue')['default']
    OutboundLink: typeof import('./theme/components/icons/OutboundLink.vue')['default']
    Page: typeof import('./theme/components/Page.vue')['default']
    PageFooter: typeof import('./theme/components/PageFooter.vue')['default']
    PluginVersion: typeof import('./theme/components/PluginVersion.vue')['default']
    PromptForUpdateImg: typeof import('./theme/components/PromptForUpdateImg.vue')['default']
    PwaHero: typeof import('./theme/components/PwaHero.vue')['default']
    PwaLogo: typeof import('./theme/components/PwaLogo.vue')['default']
    ReloadPrompt: typeof import('./theme/components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunExamples: typeof import('./theme/components/RunExamples.md')['default']
    SideBar: typeof import('./theme/components/SideBar.vue')['default']
    SideBarLinks: typeof import('./theme/components/SideBarLinks.vue')['default']
    SsrSsg: typeof import('./theme/components/SsrSsg.md')['default']
    ToggleSideBarButton: typeof import('./theme/components/ToggleSideBarButton.vue')['default']
  }
}

export {}
