export const commands = [
  'npx tsup src/index.ts --dts --target esnext --external @vite-pwa/assets-generator --format cjs,esm',
  'npx tsup src/client/build/register.ts --target esnext --format esm -d dist/client/build',
  'npx tsup src/client/build/vue.ts --external vue --target esnext --format esm -d dist/client/build',
  'npx tsup src/client/build/svelte.ts --external svelte/store --target esnext --format esm -d dist/client/build',
  'npx tsup src/client/build/react.ts --external react --target esnext --format esm -d dist/client/build',
  'npx tsup src/client/build/preact.ts --external preact/hooks --target esnext --format esm -d dist/client/build',
  'npx tsup src/client/build/solid.ts --external solid-js --target esnext --format esm -d dist/client/build',
  'npx tsup src/client/dev/register.ts --target esnext --format esm -d dist/client/dev',
  'npx tsup src/client/dev/vue.ts --external vue --target esnext --format esm -d dist/client/dev',
  'npx tsup src/client/dev/svelte.ts --external svelte/store --target esnext --format esm -d dist/client/dev',
  'npx tsup src/client/dev/react.ts --external react --target esnext --format esm -d dist/client/dev',
  'npx tsup src/client/dev/preact.ts --external preact/hooks --target esnext --format esm -d dist/client/dev',
  'npx tsup src/client/dev/solid.ts --external solid-js --target esnext --format esm -d dist/client/dev',
]
