export const commands = [
  'npx tsup src/index.ts --dts --format cjs,esm',
  'npx tsup src/client/build/register.ts --format esm -d dist/client/build',
  'npx tsup src/client/build/vue.ts --external vue --format esm -d dist/client/build',
  'npx tsup src/client/build/svelte.ts --external svelte/store --format esm -d dist/client/build',
  'npx tsup src/client/build/react.ts --external react --format esm -d dist/client/build',
  'npx tsup src/client/build/preact.ts --external preact/hooks --format esm -d dist/client/build',
  'npx tsup src/client/build/solid.ts --external solid-js --format esm -d dist/client/build',
  'npx tsup src/client/dev/register.ts --format esm -d dist/client/dev',
  'npx tsup src/client/dev/vue.ts --external vue --format esm -d dist/client/dev',
  'npx tsup src/client/dev/svelte.ts --external svelte/store --format esm -d dist/client/dev',
  'npx tsup src/client/dev/react.ts --external react --format esm -d dist/client/dev',
  'npx tsup src/client/dev/preact.ts --external preact/hooks --format esm -d dist/client/dev',
  'npx tsup src/client/dev/solid.ts --external solid-js --format esm -d dist/client/dev',
]
