name: CR

env:
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, labeled, ready_for_review]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  release:
    if: ${{ !github.event.pull_request.draft && contains(github.event.pull_request.labels.*.name, 'cr-tracked') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.0.0
      - run: pnpm install
      - run: pnpm build
      - run: pnpx pkg-pr-new publish --compact --no-template --pnpm
